### ISSUE TITLE
Node.js server doesn't start

### ISSUE THREAD

**Issue by tloyau** [flint-bot/flint#11]
Hi, I don't understand why but I move my bot from Cloud9 to a personal server, I change the webhook URL and the port, and now the server doesn't start. 

I run the command "node bot.js" and nothing appears. 

Do you have an idea? 

Thanks.

**Comment by nmarus** [comment]
Try `DEBUG=* node bot.js` to see if the debug logs mention anything. Command with be slightly different if you are on a windows box to set the env variable.

**Comment by tloyau** [comment]
It's working thanks :)
