### ISSUE TITLE
storage/redis.js file is missing in 4.5.3

### ISSUE THREAD

**Issue by guillain** [flint-bot/flint#12]
Hi,

Thanks for all because very useful :)
Just to let you know in the version 4.5.3 the storage/redis.js file has disappeared.
I know don't if it's volonteer but I placed the file of the previous version and it works like that.

Thanks again!
Guillain

**Comment by nmarus** [comment]
I pulled it as it was having some issues when restarting the service. I replaced it with a template that can be used to create your own storage driver. That said, Flint 5 will have a better way of doing this and should be out this summer.
