### ISSUE TITLE
can a bot send a message not as a reply?

### ISSUE THREAD

**Issue by pomarc** [flint-bot/flint#17]
My bot should send messages in a chatroom not after a .hears, but on some external triggers: on a timeout, on an alert and so on.
On your examples I've seen than the only object that can ".say" things is bot, and bot is usually created as a parameter for the ".hears" handler.
Is there any way to say something not after a question? 
thanks

**Comment by pomarc** [comment]
I've seen that I can use the 
`flint.bots` 

collection, as in

```
bot= flint.bots[0];
bot.say( message);
```

maybe somehow filtering by rommid. But is this a clean way todo it?

**Comment by nmarus** [comment]
The only way to do this for now is to filter/search that collection. 

If using lodash, you can use `_.filter` and `_.find` to parse this collection with very little code. 

Check out examples below and note you can use these same recipes to find/filter by any property of the bot object. The main differences between `_.filter` and `_.find` is that filter will return an array of matching objects, while find will return a single object that is first matched.

The function iterator for filter and find expects a boolean return value that indicates a match or not.

Example to find by room id:

```
const botInSpecificRoom = _.find(flint.bots, bot => (bot.room.id === 'abcdefg'));
botInSpecificRoom.say('hello');
```

If you are looking to do things with all rooms, you can use something like this:

```
_.forEach(flint.bots, bot => bot.say('This is a broadcast message."));
```

Using filter, you can do something like this based on room title:

```
// RegExp to match string starting with '#important'
const reImportant = /^#important.*/;
const bots = _.filter(flint.bots, bot => reImportant.test(bot.room.title));
_.forEach(bots, bot => bot.say('This is a broadcast message."));
```

**Comment by pomarc** [comment]
thanks
